---
- name: Desligar VM
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - name: Find folder for VM
      community.vmware.vmware_guest_find:
        hostname: '{{ credential_vcenter_hostname }}'
        password: '{{ credential_vcenter_password }}'
        username: '{{ credential_vcenter_username }}'
        validate_certs: False
        name: "{{ guest_name }}"
      delegate_to: localhost
      register: vm_folder

    - name: "Desligando {{ guest_name }}"
      vmware_guest:
